export default {
  login: "unreal0901",
  id: 80266913,
  node_id: "MDQ6VXNlcjgwMjY2OTEz",
  avatar_url: "https://avatars.githubusercontent.com/u/80266913?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/unreal0901",
  html_url: "https://github.com/unreal0901",
  followers_url: "https://api.github.com/users/unreal0901/followers",
  following_url:
    "https://api.github.com/users/unreal0901/following{/other_user}",
  gists_url: "https://api.github.com/users/unreal0901/gists{/gist_id}",
  starred_url: "https://api.github.com/users/unreal0901/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/unreal0901/subscriptions",
  organizations_url: "https://api.github.com/users/unreal0901/orgs",
  repos_url: "https://api.github.com/users/unreal0901/repos",
  events_url: "https://api.github.com/users/unreal0901/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/unreal0901/received_events",
  type: "User",
  site_admin: false,
  name: "unreal",
  company: null,
  blog: "https://cs-aditya.herokuapp.com/index.html",
  location: null,
  email: null,
  hireable: null,
  bio: "love coding",
  twitter_username: null,
  public_repos: 25,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2021-03-08T14:06:06Z",
  updated_at: "2021-05-30T18:21:19Z",
};
